### PR TITLE
Created Add and Edit Employee Pages as well as edited some others

### PR DESCRIPTION
**Pull request by AJ-Schulte**
I add a search box to the Home Page. I also created a check box both in sign up and user pages that will confirm whether user is a supervisor. I made it so you can't sign up without a username and password. Edited a few other things.

### CODE REVIEW

**Comment by Ethan-Standridge** [comment]
Just a couple questions:
You commented out the save() function of EmployeeDemographics. Was there a conflict? (Seriously, this was my main worry writing it.)
You changed the exception in searchDemographic() to a RuntimeException. Why?
Also, just a tip: you can start the comments on stuff to add in AddEmployee with TODO: and VS will highlight it like an error. Might be easier to find later.

**Comment by AJ-Schulte** [comment]
> Just a couple questions: You commented out the save() function of EmployeeDemographics. Was there a conflict? (Seriously, this was my main worry writing it.) You changed the exception in searchDemographic() to a RuntimeException. Why? Also, just a tip: you can start the comments on stuff to add in AddEmployee with TODO: and VS will highlight it like an error. Might be easier to find later.

The Save function duplicated the Employees so there were 2 of each employee instead of just 1. And I had an error trying to run the searchDemographic() without changing it to a RuntimeException. The last bit of info I didn't know and I can do that later if you need it, otherwise it should be fine.

**Comment by Ethan-Standridge** [comment]
I'M STUPID. The issue wasn't in save(), it was in arrayGen(). I called TempArray.add... on Demographics like all the other classes and it meant it got entered into the base twice, once from .add and once from its own constructor. Just remove the TempArray.add part and it should fix it.
Screenshot 2024-04-19 182227
Screenshot 2024-04-19 182154

For searchDemographic(), was it an unhandled error exception? It throws an exception in case the input is invalid and it can't find a matching EmployeeDemographic. You can just add `throws Exception` to the declaration of the method that calls it if you don't want to deal with it, or use try-catch Exception if you want to handle that case. The main method in Testing has a throws Exception clause if you want to see an example - in that case, the exception will be thrown all the way to the terminal. The alternative would be to return `null` if it can't find anything, but you'd have to stay aware that it could return that.
exception

**Comment by AJ-Schulte** [comment]
> I'M STUPID. The issue wasn't in save(), it was in arrayGen(). I called TempArray.add... on Demographics like all the other classes and it meant it got entered into the base twice, once from .add and once from its own constructor. Just remove the TempArray.add part and it should fix it. Screenshot 2024-04-19 182227 Screenshot 2024-04-19 182154
> 
> For searchDemographic(), was it an unhandled error exception? It throws an exception in case the input is invalid and it can't find a matching EmployeeDemographic. You can just add `throws Exception` to the declaration of the method that calls it if you don't want to deal with it, or use try-catch Exception if you want to handle that case. The main method in Testing has a throws Exception clause if you want to see an example - in that case, the exception will be thrown all the way to the terminal. The alternative would be to return `null` if it can't find anything, but you'd have to stay aware that it could return that. exception

**Comment by AJ-Schulte** [comment]
Whenever I tried running it with the throw exception in the declaration it jsut gave me an error and wouldn't run anything so I had to change it to get it to run anything

**Pull request merged**
